version: '3.3'

services:
  parsr:
    build:
      context: .
      dockerfile: docker/parsr/Dockerfile
      args:
        DEV_MODE: 'true'
    ports:
      - 3001:3001
    environment:
      ABBYY_SERVER_URL:
    volumes:
      - ./pipeline/:/opt/app-root/src/api/server/dist/output

volumes:
  pipeline:
    driver: local
