version: '3.3'

services:
  # parsr-base is the base image with all the dependencies already installed on it
  # just build it if you need new dependencies otherwise use the publish one
  parsr-base:
    image: axarev/parsr-base
    build:
      context: .
      dockerfile: docker/parsr-base/Dockerfile

  # parsr API 
  parsr:
    image: axarev/parsr
    build:
      context: .
      dockerfile: docker/parsr/Dockerfile
      args:
        DEV_MODE: 'true'
    ports:
      - 3001:3001
    environment:
      ABBYY_SERVER_URL:
    volumes:
      - ./pipeline/:/opt/app-root/src/api/server/dist/output

volumes:
  pipeline:
    driver: local
